extends:
  - eslint:recommended
  - plugin:react/recommended
root: true
env:
  es6: true
  browser: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
plugins:
  - react
rules:
  arrow-parens: [error, as-needed]
  comma-dangle: [error, always-multiline]
  indent: [error, 2, {SwitchCase: 1}]
  no-multiple-empty-lines: [error, {max: 1, maxBOF: 0, maxEOF: 0}]
  no-unused-vars: [error, {argsIgnorePattern: "^__$"}]
  semi: [error, always]
  space-before-function-paren: [error, {anonymous: always, named: never}]
